// <auto-generated />
using System;
using GrillMaster.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GrillMaster.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260906021240_AddOrderStatus")]
    partial class AddOrderStatus
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GrillMaster.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Grilled Beef"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Grilled Chicken"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Grilled Seafood"
                        });
                });

            modelBuilder.Entity("GrillMaster.Models.MenuItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("MenuItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Name = "Beef Steak",
                            Price = 500m
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            Name = "Beef Kofta",
                            Price = 350m
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 2,
                            Name = "Grilled Chicken",
                            Price = 300m
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 3,
                            Name = "Seafood Platter",
                            Price = 800m
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 1,
                            Name = "Beef Skewers",
                            Price = 300m
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 2,
                            Name = "Double Burger",
                            Price = 250m
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 1,
                            Name = "Mixed Grill Platter",
                            Price = 650m
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 2,
                            Name = "Pizza",
                            Price = 250m
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 2,
                            Name = "Meatball Pasta",
                            Price = 300m
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 3,
                            Name = "Grilled Shrimp",
                            Price = 450m
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 2,
                            Name = "Grilled Chicken Wings",
                            Price = 250m
                        });
                });

            modelBuilder.Entity("GrillMaster.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("GrillMaster.Models.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("MenuItemId")
                        .HasColumnType("int");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("MenuItemId");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("GrillMaster.Models.MenuItem", b =>
                {
                    b.HasOne("GrillMaster.Models.Category", "Category")
                        .WithMany("MenuItems")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("GrillMaster.Models.OrderItem", b =>
                {
                    b.HasOne("GrillMaster.Models.MenuItem", "MenuItem")
                        .WithMany()
                        .HasForeignKey("MenuItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GrillMaster.Models.Order", "Order")
                        .WithMany("Items")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MenuItem");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("GrillMaster.Models.Category", b =>
                {
                    b.Navigation("MenuItems");
                });

            modelBuilder.Entity("GrillMaster.Models.Order", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
